### PR TITLE
Add git ssh support

### PR DESCRIPTION
**Pull request by leki75**
* installed openssh-client and su-exec packages
* added ssh key as a secret to the container
* changed nobody user to katafygio to have a home directory for ssh keys
* used entrypoint.sh to set ssh key and config at runtime

### CODE REVIEW

**Comment by bpineau** [comment]
Thanks for submitting this @leki75!

The patch is correct, but changing the process uid would bite existing users having data.

Would you mind mouting the secrets with `mountPath: "/.ssh"` (as / is `nobody`'s home) and settings `securityContext.fsGroup: 65534`?

That should be enough to consume ssh key from an unmodified image (except openssh-client package addition). As a bonus, secrets changes will propagate.

**Comment by leki75** [comment]
Thank you for your comments! I have added a new commit where I do all the modifications you suggested. I was curious that mounting the secrets in /.ssh works and it does!

**Comment by MaxDiOrio** [comment]
When do we think this will be merged and available in Docker?  This merge should allow using SSH to store the backups in AWS CodeCommit.

**Comment by bpineau** [comment]
Thanks for the PR and for your patience @leki75 !
@MaxDiOrio understood; I'll push a new release (including to Docker hub) today.

**Pull request merged**
